name: Deploy plugin

on:
  push:
    branches: [main, beta, alpha]

jobs:
  deploy-git-tag-and-push-npm: 
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create git tag 
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm ci

    - name: Install self so that semantic-release can use it during deployment 
      run: |
        npm run compile
        npm pack
        npm install --no-save semantic-release-precheck-1.0.0.tgz

    - name: Deploy git tag via semantic-release
      uses: cycjimmy/semantic-release-action@v4
      with:
        extra_plugins: |
          conventional-changelog-conventionalcommits
          @semantic-release/github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_PUSH_TOKEN }}